(() => {
  'use strict';
  const $=id=>document.getElementById(id),clone=v=>JSON.parse(JSON.stringify(v));
  const CAL_KEY='family-music-quest-calibration-v1',RESULT_KEY='family-music-quest-hardware-results-v1';
  let unsubAudio=null,unsubMidi=null,levelSamples=[],peak=0,events=[],tests={};
  const activeId=()=>window.FMQProfiles?.getActiveProfile()?.id||'no-profile';
  const getJson=(key,fallback={})=>{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback;}catch{return fallback;}};
  const setJson=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  function platform(){return{userAgent:navigator.userAgent,platform:navigator.userAgentData?.platform||navigator.platform||'Unknown',language:navigator.language};}
  function calibration(){const all=getJson(CAL_KEY);return all[activeId()]||{};}
  function saveCalibration(patch){const all=getJson(CAL_KEY);all[activeId()]={...(all[activeId()]||{}),...patch,updatedAt:Date.now()};setJson(CAL_KEY,all);renderCalibration();}
  function renderCalibration(){const c=calibration(),el=$('diagCalibration');if(el)el.textContent=c.microphone?`Saved setup · noise floor ${Number(c.microphone.noiseFloor||0).toFixed(4)} · gate ${Number(c.microphone.noiseGate||0).toFixed(4)}`:'No saved setup for this player and device.';}
  function open(){const root=$('hardwareDiagnostics');root.hidden=false;showTab('microphone');renderCalibration();refreshReport();}
  function close(){stopAudio();window.FMQHardware?.midi.destroy();unsubMidi?.();unsubMidi=null;$('hardwareDiagnostics').hidden=true;}
  function showTab(name){document.querySelectorAll('.diagnostic-view').forEach(v=>v.hidden=v.dataset.diagView!==name);document.querySelectorAll('[data-diag-tab]').forEach(b=>b.classList.toggle('active',b.dataset.diagTab===name));}
  async function startAudio(){
    const audio=window.FMQGuitarAudio;if(!audio)throw new Error('Guitar input service is still loading.');
    levelSamples=[];peak=0;if(!audio.active)await audio.start(calibration().microphone?.deviceId||'');
    unsubAudio?.();unsubAudio=audio.subscribe(reading=>{levelSamples.push(reading.rms);if(levelSamples.length>240)levelSamples.shift();peak=Math.max(peak,reading.rms);const midi=reading.freq?Math.round(69+12*Math.log2(reading.freq/440)):null,cents=reading.freq?(69+12*Math.log2(reading.freq/440)-midi)*100:0;
      $('diagMicLevel').style.width=`${Math.min(100,reading.rms*1600)}%`;$('diagMicNote').textContent=reading.note||'—';$('diagMicDetails').textContent=`${reading.freq?reading.freq.toFixed(1)+' Hz':'No stable pitch'} · ${reading.freq?cents.toFixed(0)+' cents':'—'} · onset ${reading.onset?'YES':'no'} · ${reading.rms>audio.noiseGate&&reading.freq?'would be considered':'not scoreable yet'}`;
      if(reading.onset||reading.freq)events.unshift({time:new Date().toISOString(),kind:'microphone',note:reading.note,frequency:reading.freq,rms:reading.rms,onset:reading.onset,accepted:Boolean(reading.freq&&reading.rms>audio.noiseGate)});events=events.slice(0,100);
    });
    const track=audio.stream?.getAudioTracks()[0],settings=track?.getSettings?.()||{};$('diagMicDevice').textContent=track?.label||'Default microphone';$('diagMicSettings').textContent=`Permission granted · ${audio.context?.sampleRate||settings.sampleRate||'—'} Hz · ${settings.channelCount||1} channel · echo cancellation ${String(settings.echoCancellation??'browser choice')} · noise suppression ${String(settings.noiseSuppression??'browser choice')} · auto gain ${String(settings.autoGainControl??'browser choice')}`;
  }
  function stopAudio(){unsubAudio?.();unsubAudio=null;window.FMQGuitarAudio?.stop();}
  function calibrate(){if(levelSamples.length<10){$('diagMicDetails').textContent='Listen for a few seconds of quiet room sound first.';return;}const sorted=[...levelSamples].sort((a,b)=>a-b),noiseFloor=sorted[Math.floor(sorted.length*.8)]||0,noiseGate=Math.max(.005,Math.min(.08,noiseFloor*2.4));saveCalibration({microphone:{deviceId:window.FMQGuitarAudio?.deviceId||'',noiseFloor,noiseGate,peak,sampleRate:window.FMQGuitarAudio?.context?.sampleRate||null}});tests.microphone={available:true,noiseFloor,peak,calibrated:true};persistResults();}
  async function connectMidi(){
    const service=window.FMQHardware.midi;unsubMidi?.();unsubMidi=service.subscribe(event=>{const s=service.snapshot();$('diagMidiDevice').textContent=s.input?`${s.input.name}${s.input.manufacturer?' · '+s.input.manufacturer:''}`:'No MIDI input found';if(event.type==='noteon'||event.type==='noteoff'||event.type==='controlchange'){events.unshift({time:new Date().toISOString(),kind:'midi',type:event.type,note:event.note,midi:event.midi,velocity:event.velocity,channel:event.channel,controller:event.controller,value:event.value,polyphony:event.polyphony});events=events.slice(0,100);tests.midi={available:true,deviceDetected:Boolean(s.input),noteOn:tests.midi?.noteOn||event.type==='noteon',noteOff:tests.midi?.noteOff||event.type==='noteoff',velocity:tests.midi?.velocity||event.type==='noteon'&&event.velocity>0,polyphony:tests.midi?.polyphony||event.polyphony>=2,sustain:tests.midi?.sustain||event.controller===64};persistResults();renderMidiEvent(event);}});const snapshot=await service.connect();$('diagMidiStatus').textContent=snapshot.input?'MIDI ready':'Web MIDI is available, but no keyboard is connected.';tests.midi={...(tests.midi||{}),available:true,deviceDetected:Boolean(snapshot.input)};persistResults();
  }
  function renderMidiEvent(e){$('diagMidiEvent').textContent=e.type==='controlchange'?`Control ${e.controller} · value ${e.value}${e.controller===64?` · sustain ${e.sustain?'ON':'off'}`:''}`:`${e.type==='noteon'?'Note On':'Note Off'} · ${e.note} · MIDI ${e.midi} · velocity ${e.velocity} · channel ${e.channel}`;$('diagMidiHeld').textContent=e.held.length?`Held: ${e.held.map(window.FMQHardware.noteName).join(', ')} · ${e.polyphony} notes`:'No keys held';}
  function persistResults(){const all=getJson(RESULT_KEY);all[activeId()]={tests:clone(tests),events:events.slice(0,100),updatedAt:Date.now(),platform:platform()};setJson(RESULT_KEY,all);refreshReport();}
  function reportObject(){const profile=window.FMQProfiles?.getActiveProfile(),saved=getJson(RESULT_KEY)[activeId()]||{};return{format:'family-music-quest-hardware-report',version:1,generatedAt:new Date().toISOString(),player:profile?{id:profile.id,name:profile.name}:null,platform:platform(),calibration:calibration(),results:saved.tests||tests,recentEvents:saved.events||events};}
  function reportText(r=reportObject()){const mic=r.results?.microphone||{},midi=r.results?.midi||{};return[`Family Music Quest Hardware Validation`,`Player: ${r.player?.name||'Unknown'}`,`Platform: ${r.platform.platform}`,`Microphone calibration: ${mic.calibrated?'PASS':'NOT RUN'}`,`Noise floor: ${mic.noiseFloor?.toFixed?.(4)||'—'}`,`MIDI available: ${midi.available?'PASS':'NOT TESTED'}`,`MIDI device: ${midi.deviceDetected?'PASS':'NOT DETECTED'}`,`Note On: ${midi.noteOn?'PASS':'NOT TESTED'}`,`Note Off: ${midi.noteOff?'PASS':'NOT TESTED'}`,`Velocity: ${midi.velocity?'PASS':'NOT TESTED'}`,`Polyphony: ${midi.polyphony?'PASS':'NOT TESTED'}`,`Sustain: ${midi.sustain?'PASS':'NOT TESTED'}`].join('\n');}
  function refreshReport(){$('diagReport').textContent=reportText();}
  function download(name,data,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
  function exportBackup(){const payload={format:'family-music-quest-backup',version:1,createdAt:new Date().toISOString(),profiles:window.FMQProfiles.exportStore(),calibration:getJson(CAL_KEY),hardwareResults:getJson(RESULT_KEY),preferences:{instrument:localStorage.getItem('family-music-instrument-v1')}};download(`family-music-quest-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload,null,2));}
  async function restoreBackup(file){let data;try{data=JSON.parse(await file.text());}catch{throw new Error('That file is not valid JSON.');}if(data?.format!=='family-music-quest-backup'||data.version!==1||!data.profiles?.profiles)throw new Error('That is not a Family Music Quest backup.');if(!confirm(`Restore ${data.profiles.profiles.length} player profile(s)? Current player progress will be replaced.`))return;if(!window.FMQProfiles.replaceStore(data.profiles))throw new Error('The profile data did not pass validation.');if(data.calibration)setJson(CAL_KEY,data.calibration);if(data.hardwareResults)setJson(RESULT_KEY,data.hardwareResults);if(data.preferences?.instrument)localStorage.setItem('family-music-instrument-v1',data.preferences.instrument);alert('Backup restored. Family Music Quest will reload now.');location.reload();}
  document.addEventListener('DOMContentLoaded',()=>{
    $('openDiagnostics').onclick=open;$('closeDiagnostics').onclick=close;document.querySelectorAll('[data-diag-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.diagTab));
    $('diagStartMic').onclick=()=>startAudio().catch(e=>$('diagMicDetails').textContent=e.message);$('diagStopMic').onclick=stopAudio;$('diagCalibrate').onclick=calibrate;$('diagConnectMidi').onclick=()=>connectMidi().catch(e=>$('diagMidiStatus').textContent=e.message);
    $('diagCopyReport').onclick=()=>navigator.clipboard?.writeText(reportText());$('diagExportReport').onclick=()=>download('family-music-quest-hardware-report.json',JSON.stringify(reportObject(),null,2));$('diagReset').onclick=()=>{const all=getJson(RESULT_KEY);delete all[activeId()];setJson(RESULT_KEY,all);tests={};events=[];refreshReport();};
    $('exportBackup').onclick=exportBackup;$('restoreBackup').onchange=e=>restoreBackup(e.target.files[0]).catch(err=>alert(err.message));
  });
  window.FMQDiagnostics={reportObject,reportText,calibration,open};
})();
