const assert=require('assert');global.window={};
const book=require('./piano-songbook.js');
assert.equal(book.publicDomain.length,5);
assert.equal(book.originals.length,6);
assert.equal(new Set(book.songs.map(s=>s.id)).size,book.songs.length);
book.songs.forEach(song=>{
  assert(song.notes.length>20&&song.measureCount>=6);
  assert(song.targetDuration>=15,`${song.id} has an implausibly short generated timeline`);
  assert(song.phraseBoundaries.length>=3);
  song.notes.forEach(note=>{assert(Number.isFinite(note.beat)&&note.beat>=0);assert(note.durationBeats>0);assert(Number.isFinite(note.start)&&Number.isFinite(note.duration));assert(Number.isFinite(note.velocity)&&note.velocity>=1&&note.velocity<=127);assert(note.articulation>0&&note.articulation<=1);});
  assert(Math.max(...song.notes.map(n=>n.beat+n.durationBeats))<=song.measureCount*4,'events must remain inside declared measures');
  assert(song.notes.some((n,i)=>song.notes.some((m,j)=>i!==j&&m.beat===n.beat)),`${song.id} needs simultaneous arrangement events`);
  const listen=book.arrangement(song,'listen','screen');assert.equal(listen.player.length,song.notes.length);
  const mic=book.arrangement(song,'melody','microphone');assert(mic.accompaniment.length>0);for(let i=1;i<mic.player.length;i++)assert(Math.abs(mic.player[i].start-mic.player[i-1].start)>=.02,'microphone arrangement must be monophonic');
  const together=book.arrangement(song,'full','midi');assert.equal(together.player.length,song.notes.length);assert(together.player.some((n,i)=>together.player.some((m,j)=>i!==j&&m.start===n.start)));
  assert(book.arrangement(song,'left','midi').player.every(n=>n.hand==='left'));
  assert(book.arrangement(song,'right','midi').player.every(n=>n.hand==='right'));
});
book.publicDomain.forEach(song=>{assert.equal(song.rights.status,'Public Domain');assert(song.rights.source.startsWith('https://'));assert(song.rights.arrangement.includes('Family Music Quest'));assert.equal(song.rights.lyrics,false);});
assert.equal(book.version,2);
assert.equal(book.manifest.length,book.songs.length);
assert.deepEqual(Object.fromEntries(book.publicDomain.map(song=>[song.id,song.tempo])),{'songbook-twinkle':104,'songbook-frere-jacques':112,'songbook-row-row':108,'songbook-jingle-bells':116,'songbook-ode-to-joy':104});
book.manifest.forEach(item=>{assert(item.composer&&item.arrangement&&item.source);assert(Number.isFinite(item.approximateDuration));assert(item.measureCount>0);});
const forms=Object.fromEntries(book.publicDomain.map(song=>[song.id,song.form]));
assert.deepEqual(forms['songbook-twinkle'],['A · Opening','B · Stars Above','A · Return','Ending']);
assert.deepEqual(forms['songbook-frere-jacques'],['A · Calling','B · Morning Bells','C · Ringing','D · Ding Dang Dong','Ending']);
assert.deepEqual(forms['songbook-row-row'],['A · Row the Boat','B · Merrily','Ending']);
assert.deepEqual(forms['songbook-ode-to-joy'],['A · Joy Theme','A2 · Answer','B · Together','A · Return']);
book.songs.forEach(song=>assert(song.form.some(label=>/Ending|Return|Coda|Home/i.test(label)),`${song.id} needs an intentional closing section`));
console.log('Piano songbook and arrangement tests passed');
